# Generated by Django 4.2.4 on 2023-09-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name_plural': 'Musicians'},
        ),
    ]
